name: Update Wiki File
description: Updates the wiki file with data from the repository.
author: Your Name
inputs:
  token:
    description: GitHub token to bypass branch protection rules
    required: true
  repo:
    description: The target repository (owner/repo)
    required: true
runs:
  using: "composite"
  steps:
    - run: ./entrypoint.sh
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        REPO: ${{ inputs.repo }}